service: portfolio-backend

plugins:
  - serverless-offline
  - serverless-plugin-typescript

provider:
  name: aws
  runtime: nodejs16.x
  stage: dev
  region: ap-south-1
  memorySize: 192
  timeout: 60

functions:
  app-api:
    handler: src/index.handler
    events:
      - http:
          path: /
          method: get
      - http:
          path: /{proxy+}
          method: any
    environment: ${file(env.json)}
